import fs from "fs";
import path from "path";

const SRC_DIR_1 = path.join(process.cwd(), "public", "assets", "products");
const SRC_DIR_2 = path.join(process.cwd(), "public", "products");
const OUTPUT_FILE = path.join(process.cwd(), "src", "data", "productAssetManifest.ts");

interface ManifestEntry {
  default: string | null;
  variants: Record<string, string>;
}

export function generateManifest() {
  const manifest: Record<string, ManifestEntry> = {};

  const scanDirectory = (dir: string, webPrefix: string) => {
    if (!fs.existsSync(dir)) return;

    const files = fs.readdirSync(dir);
    for (const file of files) {
      const ext = path.extname(file).toLowerCase();
      if (![".png", ".webp", ".avif", ".jpg", ".jpeg"].includes(ext)) {
        continue;
      }

      const basename = path.basename(file, ext);
      // Example: "asam-black-tea-16oz" or "asam-black-tea"
      // Split by dash to extract size code
      // Wait, some product IDs contain dashes (e.g. "asam-black-tea")
      // We want to detect if the end matches a size code.
      // Sizes are typically: "16oz", "22oz", "premium", "standard", "8oz", etc.
      const sizePattern = /-(16oz|22oz|8oz|premium|standard|12oz)$/i;
      const match = basename.match(sizePattern);

      if (match) {
        const sizeCode = match[1].toLowerCase();
        const productId = basename.replace(sizePattern, "");
        const webPath = `${webPrefix}/${file}`;

        if (!manifest[productId]) {
          manifest[productId] = { default: null, variants: {} };
        }
        manifest[productId].variants[sizeCode] = webPath;
      } else {
        const productId = basename;
        const webPath = `${webPrefix}/${file}`;

        if (!manifest[productId]) {
          manifest[productId] = { default: null, variants: {} };
        }
        manifest[productId].default = webPath;
      }
    }
  };

  scanDirectory(SRC_DIR_1, "/assets/products");
  scanDirectory(SRC_DIR_2, "/products");

  // Format code output
  const content = `// DULLY'S PRODUCT ASSET MANIFEST
// Automatically generated by scripts/generate-manifest.ts
// Do not modify manually.

export interface ManifestAsset {
  default: string | null;
  variants: Record<string, string>;
}

export const productAssetManifest: Record<string, ManifestAsset> = ${JSON.stringify(manifest, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`Successfully generated static product asset manifest at ${OUTPUT_FILE}`);
}

// If run directly
const isDirectRun = process.argv[1] && (process.argv[1].endsWith("generate-manifest.ts") || process.argv[1].endsWith("generate-manifest.js") || process.argv[1].includes("generate-manifest"));
if (isDirectRun) {
  generateManifest();
}
