// DULLY'S PRODUCT ASSET MANIFEST
// Automatically generated by scripts/generate-manifest.ts
// Do not modify manually.
// Generated at: 2026-07-11T15:57:26.312Z

export interface ManifestAsset {
  default: string | null;
  variants: Record<string, string>;
}

export const productAssetManifest: Record<string, ManifestAsset> = {};
