// DULLY'S PRODUCT ASSET MANIFEST
// Automatically generated by scripts/generate-manifest.ts
// Do not modify manually.

export interface ManifestAsset {
  default: string | null;
  variants: Record<string, string>;
}

export const productAssetManifest: Record<string, ManifestAsset> = {};
